apiVersion: batch/v1
kind: Job
metadata:
  name: helloworldjobv1
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: istio-installation-v1
        image: rohita/istio-install:latest
        envFrom:
          - secretRef:
              name: ra-secret
        command: ["/bin/bash", "./istio_install.sh"]
      restartPolicy: Never
